apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgresql.database | b64enc }}