apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-app"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  completions: 1
  backoffLimit: 6
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: webapp
          image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: postgres-svc.{{ .Values.namespace }}.svc.cluster.local
            - name: DB_PORT
              value: {{ .Values.postgresql.port | quote }}
            - name: DB_DATABASE
              value: {{ .Values.postgresql.database | quote }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-db-secret"
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-db-secret"
                  key: DB_PASSWORD
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "3.5Gi"
              cpu: "2"

      restartPolicy: OnFailure
