apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: producer-job-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: producer-job-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: producer-job-role
  apiGroup: rbac.authorization.k8s.io
