apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: producer-job-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "create", "get", "list", "watch", "update", "patch", "delete" ]
