apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-db-secret"
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.postgresql.username | b64enc }}
  DB_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  FLYWAY_PASSWORD: {{ .Values.secret.flyway_password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secret.dockerconfigjson  }}
